### ISSUE TITLE
No suitable driver found for jdbc:mysql://localhost:3306/db

### ISSUE THREAD

**Issue by evgsemenov** [evgsemenov/6.3.2_SQL#1]
Не запускается приложение после запуска контейнера. Также не удается получить доступ к БД через DBeaver (ошибка "No suitable driver found for jdbc:mysql://localhost:3306/db")

Шаги воспроизведения:
1. Склонировать репо
2. Открыть в IDEA 
3. В консоли ввести команду `docker-compose up`
4. После запуска базы данных ввести команду` java -jar artifacts/app-deadline.jar -P:jdbc.url=localhost:3306/db -P:jdbc.user=user -P:jdbc.password=pass`

ОР:
Приложение запускается

ФР:
Приложение не запускается.
В логах содержится информация об отсутствии драйвера jdbc
![Screenshot_1](https://user-images.githubusercontent.com/39197351/128635508-b2d0dfb8-be10-4a87-a8d8-873a03bbb764.png)

![Screenshot_2](https://user-images.githubusercontent.com/39197351/128635613-fc3925f7-2168-4742-9cbd-e7d46c4d6dd1.png)

**Comment by andrew-pahomov** [comment]
Доброе утро.
